steps:
  - label: build
    command:
      - nix-shell --run 'nix-build -I ssh-key=$HOME/.ssh/id_rsa -A dscp-servers'
    timeout_in_minutes: 180
    agents:
      nix: true

  # FIXME: deduplicate commands between deployments
  - label: nixops production
    command:
      # This is fun when it needs to restart the BK agent service =)
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-tmp --include builder'

      # Abort if the statefile is locked by wrapper script
      - stat /var/lib/buildkite-agent/.nixops/nixops-lock && exit 1
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-tmp --exclude builder witness0 --allow-reboot'
      - sleep 2m
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-tmp --include witness0 --allow-reboot'
    timeout_in_minutes: 180
    branches: master
    agents:
      queue: dscp
      production: true

  - label: nixops staging
    command:
      # This is fun when it needs to restart the BK agent service =)
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-stg --include builder'

      # Abort if the statefile is locked by wrapper script
      - stat /var/lib/buildkite-agent/.nixops/nixops-lock && exit 1
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-stg --exclude builder witness0 --allow-reboot'
      - sleep 2m
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-stg --include witness0 --allow-reboot'
    timeout_in_minutes: 180
    branches: develop
    agents:
      queue: dscp
      staging: true
