steps:
  - label: build
    command: nix-shell --run 'nix-build -I ssh-key=$HOME/.ssh/id_rsa -A dscp-servers'
    agents:
      queue: dscp

  - label: nixops
    command:
      - nix-shell --run 'nixops deploy -d dscp-stg --include builder'
      # - nix-shell --run 'nixops deploy -d dscp-stg --exclude builder --exclude witness-internal --allow-reboot'
      # - nix-shell --run 'nixops deploy -d dscp-stg --include witness-internal --allow-reboot'
    branches: develop
    agents:
      queue: dscp
