steps:
  - label: build
    command: nix-shell --run 'nix-build -I ssh-key=$HOME/.ssh/id_rsa -A dscp-servers'
    agents:
      queue: dscp

  - label: nixops
    command: nix-shell --run 'env'
    agents:
      queue: dscp
