steps:
  - label: build
    command:
      - nix-shell --run 'nix-build -I ssh-key=$HOME/.ssh/id_rsa -A dscp-servers'
    timeout_in_minutes: 180
    agents:
      queue: dscp

  - label: deploy staging
    command:
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-tmp --include builder'
      # Abort if the statefile is locked by wrapper script
      - stat /var/lib/buildkite-agent/.nixops/nixops-lock && exit 1
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-tmp --exclude builder witness0 --allow-reboot'
      - sleep 2m
      - sudo -u nixops nix-shell --run 'nixops deploy -d dscp-tmp --include witness0 --allow-reboot'
    timeout_in_minutes: 180
    branches: master
    agents:
      queue: dscp
      deploy-target: staging
